version: '3'

services:
  goomer-lista-rango-pg:
    image: bitnami/postgresql
    ports:
      - 5432:5432
    environment: 
      - POSTGRESQL_USERNAME=goomer
      - POSTGRESQL_PASSWORD=goomer123
      - POSTGRESQL_DATABASE=goomer-lista-rango-db
    volumes:
      - ./src/database/init.sql:/docker-entrypoint-initdb.d/init.sql
